version: '3.3'

services:
  app:
    env_file: ".env"
    build:
      context: services/app
      dockerfile: Dockerfile.production
    ports:
      - "${APP_PORT}:${APP_PORT}"

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
