version: '3.3'

services:
  app:
    env_file: ".env"
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: npm start
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"

  nginx:
    build:
      context: services/nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      # - "./services/nginx/devopsanton.conf:/etc/nginx/conf.d/devopsanton.conf"
      - "./services/nginx/maintenance.html:/etc/nginx/html/maintenance.html"
